// Ablation + prototype lab for the `smart` bot line, feeding
// docs/researches/2026-08-11-smart-ablation-and-ev.md.
//
// Every variant is measured the same way: head-to-head against `balanced`,
// the incumbent, across the (victory target x dice set) grid. That is a much
// cheaper and sharper question than a full round robin — "does this rule beat
// the bot it was grafted onto?" — so the match count per cell can be high
// enough to resolve the ~1pp effects the 5 000-match round robin could not.
//
// Variants live here rather than in `PRESETS` on purpose: `PRESET_NAMES`
// drives the opponent picker in the web setup screen, and these are research
// scaffolding, not personalities to offer a player.
import { runSimulation, createPreset, ThresholdBot, PRESETS } from '@farkle/bots';
import { DICE, DICE_PER_TURN } from '@farkle/engine';

const MATCHES = Number(process.argv[2] ?? 20000);
const BASE_SEED = 20260811;

const TARGETS = [1500, 3000, 8000];
const DICE_SETS = {
  ordinary: new Array(DICE_PER_TURN).fill(DICE['balanced']),
  cheat: new Array(DICE_PER_TURN).fill(DICE['cheat']),
  trinity: new Array(DICE_PER_TURN).fill(DICE['trinity']),
};

const BALANCED = PRESETS['balanced'];

/**
 * Each variant is a function of the match's victory target, because two of
 * the ideas under test are explicitly target-dependent — and the script, not
 * the bot, is what knows the target here. Returning plain `BotParams` keeps
 * every variant expressible without touching the shipped preset table.
 */
const VARIANTS = {
  // Both rules together — the already-committed `smart`, as a reference row.
  smart: () => PRESETS['smart'],

  // Rule 1 alone: target-relative bankAt, no endgame caution.
  'smart-bankat': () => ({
    ...BALANCED,
    bankAt: 410,
    bankAtTargetBase: 290,
    bankAtTargetScale: 240_000,
  }),

  // Rule 2 alone: endgame caution, ordinary fixed bankAt.
  'smart-endgame': () => ({
    ...BALANCED,
    endgameMargin: 300,
    endgameBankAt: 150,
  }),

  // New: one-ply expected-value banking, replacing bankAt/minDiceToThrow.
  'smart-ev': () => ({ ...BALANCED, evBanking: true }),

  // New: the short-race lever the round robin pointed at — `reckless` beats
  // the field at low targets with minDiceToThrow 1 and a negative diceValue,
  // and the earlier `smart` showed that copying its bankAt alone does not
  // reproduce that. So copy those two instead, only for a short race.
  'smart-risk': (target) =>
    target <= 2000 ? { ...BALANCED, minDiceToThrow: 1, diceValue: -5 } : BALANCED,
};

function pct(x) {
  return (x * 100).toFixed(1);
}

function seedFor(target, diceSetName, variant) {
  let h = BASE_SEED ^ target;
  const s = `${diceSetName}|${variant}`;
  for (let i = 0; i < s.length; i++) {
    h = (Math.imul(h, 16777619) ^ s.charCodeAt(i)) >>> 0;
  }
  return h >>> 0;
}

const started = Date.now();
console.log(`<!-- generated by scripts/dice-balance/smart-lab.mjs, ${MATCHES} matches/cell -->`);
console.log(`\nEach cell is the variant's win rate vs \`balanced\`. >50 means it beats balanced.\n`);

const summary = {};

for (const [variant, paramsFor] of Object.entries(VARIANTS)) {
  summary[variant] = [];
  console.log(`\n### ${variant} vs balanced\n`);
  console.log(`| dice | target | win% vs balanced | CI95 | farkle% | avg/bank | turns/match |`);
  console.log(`|---|---|---|---|---|---|---|`);

  for (const diceSetName of Object.keys(DICE_SETS)) {
    for (const target of TARGETS) {
      const params = paramsFor(target);
      const report = runSimulation({
        matches: MATCHES,
        seed: seedFor(target, diceSetName, variant),
        target,
        loadoutA: DICE_SETS[diceSetName],
        loadoutB: DICE_SETS[diceSetName],
        makeA: (s) => new ThresholdBot(variant, params, s),
        makeB: (s) => createPreset('balanced', s),
      });
      const [lo, hi] = report.a.winRateCI95;
      summary[variant].push(report.a.winRate);
      console.log(
        `| ${diceSetName} | ${target} | **${pct(report.a.winRate)}** | [${pct(lo)},${pct(hi)}] | ${pct(report.a.farkleRate)} | ${report.a.avgBankedPerBank.toFixed(0)} | ${report.avgTurnsPerMatch.toFixed(1)} |`,
      );
      process.stderr.write(
        `[${((Date.now() - started) / 1000).toFixed(0)}s] ${variant} ${diceSetName}/${target}: ${pct(report.a.winRate)} [${pct(lo)},${pct(hi)}]\n`,
      );
    }
  }
}

console.log(`\n### Summary: mean win% vs balanced across all 9 conditions\n`);
console.log(`| variant | mean | worst | best |`);
console.log(`|---|---|---|---|`);
for (const [variant, rates] of Object.entries(summary)) {
  const mean = rates.reduce((s, x) => s + x, 0) / rates.length;
  console.log(`| ${variant} | **${pct(mean)}** | ${pct(Math.min(...rates))} | ${pct(Math.max(...rates))} |`);
}

process.stderr.write(`done in ${((Date.now() - started) / 1000).toFixed(0)}s\n`);
