// Screening pass for the four new evBanking refinements from
// docs/researches/2026-08-10-smart-ablation-and-ev.md's open questions:
// evCapToTarget, evCatchUpTurns, evKeepSelection, and diceValue:0 (the cheap
// consistency check between expectedKeepValue's max-points assumption and
// what the bot's own keep policy actually takes).
//
// Same method as smart-lab.mjs: each variant vs `balanced` head-to-head
// across the 3-target x 3-dice-set grid. Lower match count than the
// confirmed-result reports (this is a screening pass to pick a combination
// worth a high-N confirmation run, not the final numbers).
import { runSimulation, createPreset, ThresholdBot, PRESETS } from '@farkle/bots';
import { DICE, DICE_PER_TURN } from '@farkle/engine';

const MATCHES = Number(process.argv[2] ?? 8000);
const BASE_SEED = 20260811;

const TARGETS = [1500, 3000, 8000];
const DICE_SETS = {
  ordinary: new Array(DICE_PER_TURN).fill(DICE['balanced']),
  cheat: new Array(DICE_PER_TURN).fill(DICE['cheat']),
  trinity: new Array(DICE_PER_TURN).fill(DICE['trinity']),
};

const BALANCED = PRESETS['balanced'];
const EV = { ...BALANCED, evBanking: true };

const VARIANTS = {
  // Point 4: does the bot's own keep policy (diceValue 15, inherited from
  // balanced) undermine the max-points assumption expectedKeepValue makes?
  'ev-dv0': () => ({ ...EV, diceValue: 0 }),

  // Point 1a alone.
  'ev-cap': () => ({ ...EV, evCapToTarget: true }),

  // Point 1b alone.
  'ev-catchup': () => ({ ...EV, evCatchUpTurns: 1 }),

  // Point 1, combined.
  'ev-cap-catchup': () => ({ ...EV, evCapToTarget: true, evCatchUpTurns: 1 }),

  // Point 2 alone.
  'ev-keep': () => ({ ...EV, evKeepSelection: true }),

  // Best guess at composing 1+2.
  'ev-full': () => ({ ...EV, evCapToTarget: true, evCatchUpTurns: 1, evKeepSelection: true }),

  // Point 5: does the old smart-risk lever (minDiceToThrow/diceValue on a
  // short race) still add anything once layered under EV banking + 1a/1b?
  // evBanking already ignores minDiceToThrow entirely, so only diceValue
  // survives as a lever here — and evKeepSelection would override diceValue
  // in the ranking, so this variant deliberately leaves it off.
  'ev-risk': (target) => ({
    ...EV,
    evCapToTarget: true,
    evCatchUpTurns: 1,
    diceValue: target <= 2000 ? -5 : 15,
  }),
};

function pct(x) {
  return (x * 100).toFixed(1);
}

function seedFor(target, diceSetName, variant) {
  let h = (BASE_SEED ^ target) >>> 0;
  const s = `v2|${diceSetName}|${variant}`;
  for (let i = 0; i < s.length; i++) {
    h = (Math.imul(h, 16777619) ^ s.charCodeAt(i)) >>> 0;
  }
  return h >>> 0;
}

const started = Date.now();
console.log(`<!-- generated by scripts/dice-balance/smart-v2-lab.mjs, ${MATCHES} matches/cell -->`);
console.log(`\nEach cell is the variant's win rate vs \`balanced\`.\n`);

const summary = {};

for (const [variant, paramsFor] of Object.entries(VARIANTS)) {
  summary[variant] = [];
  console.log(`\n### ${variant} vs balanced\n`);
  console.log(`| dice | target | win% vs balanced | CI95 |`);
  console.log(`|---|---|---|---|`);

  for (const diceSetName of Object.keys(DICE_SETS)) {
    for (const target of TARGETS) {
      const params = paramsFor(target);
      const report = runSimulation({
        matches: MATCHES,
        seed: seedFor(target, diceSetName, variant),
        target,
        loadoutA: DICE_SETS[diceSetName],
        loadoutB: DICE_SETS[diceSetName],
        makeA: (s) => new ThresholdBot(variant, params, s),
        makeB: (s) => createPreset('balanced', s),
      });
      const [lo, hi] = report.a.winRateCI95;
      summary[variant].push(report.a.winRate);
      console.log(`| ${diceSetName} | ${target} | **${pct(report.a.winRate)}** | [${pct(lo)},${pct(hi)}] |`);
      process.stderr.write(
        `[${((Date.now() - started) / 1000).toFixed(0)}s] ${variant} ${diceSetName}/${target}: ${pct(report.a.winRate)} [${pct(lo)},${pct(hi)}]\n`,
      );
    }
  }
}

console.log(`\n### Summary: mean win% vs balanced across all 9 conditions\n`);
console.log(`| variant | mean | worst | best |`);
console.log(`|---|---|---|---|`);
for (const [variant, rates] of Object.entries(summary)) {
  const mean = rates.reduce((s, x) => s + x, 0) / rates.length;
  console.log(`| ${variant} | **${pct(mean)}** | ${pct(Math.min(...rates))} | ${pct(Math.max(...rates))} |`);
}

process.stderr.write(`done in ${((Date.now() - started) / 1000).toFixed(0)}s\n`);
