// Research script for docs/researches/2026-08-10-tactics-vs-victory-conditions.md
//
// Round-robins every bot preset (docs/DESIGN.md §6) against every other
// preset, under a grid of (dice set) x (victory target), and prints
// reproducible markdown tables to stdout. Consumes the *built* packages,
// same convention as the other scripts in this directory.
import { runSimulation, createPreset, PRESET_NAMES } from '@farkle/bots';
import { DICE, DICE_PER_TURN } from '@farkle/engine';

const MATCHES = Number(process.argv[2] ?? 5000);
const BASE_SEED = 20260810;

const TARGETS = [1500, 3000, 8000];
const DICE_SETS = {
  ordinary: new Array(DICE_PER_TURN).fill(DICE['balanced']),
  cheat: new Array(DICE_PER_TURN).fill(DICE['cheat']),
  trinity: new Array(DICE_PER_TURN).fill(DICE['trinity']),
};

function pct(x) {
  return (x * 100).toFixed(1);
}

function seedFor(target, diceSetName, a, b) {
  // Deterministic per-cell seed so any single cell is independently
  // reproducible without replaying the whole grid.
  let h = BASE_SEED ^ target;
  const s = `${diceSetName}|${a}|${b}`;
  for (let i = 0; i < s.length; i++) {
    h = (Math.imul(h, 16777619) ^ s.charCodeAt(i)) >>> 0;
  }
  return h >>> 0;
}

function runCell(target, diceSetName, a, b) {
  const loadout = DICE_SETS[diceSetName];
  const seed = seedFor(target, diceSetName, a, b);
  return runSimulation({
    matches: MATCHES,
    seed,
    target,
    loadoutA: loadout,
    loadoutB: loadout,
    makeA: (s) => createPreset(a, s),
    makeB: (s) => createPreset(b, s),
  });
}

const started = Date.now();
console.log(`<!-- generated by scripts/dice-balance/tactics-report.mjs, ${MATCHES} matches/cell -->`);

for (const diceSetName of Object.keys(DICE_SETS)) {
  for (const target of TARGETS) {
    const matrix = {};
    for (const p of PRESET_NAMES) matrix[p] = {};

    for (let i = 0; i < PRESET_NAMES.length; i++) {
      for (let j = i + 1; j < PRESET_NAMES.length; j++) {
        const a = PRESET_NAMES[i];
        const b = PRESET_NAMES[j];
        const report = runCell(target, diceSetName, a, b);
        matrix[a][b] = report.a.winRate;
        matrix[b][a] = report.b.winRate;
        process.stderr.write(
          `[${((Date.now() - started) / 1000).toFixed(0)}s] dice=${diceSetName} target=${target} ${a} vs ${b}: ${pct(report.a.winRate)}/${pct(report.b.winRate)} (avg ${report.avgTurnsPerMatch.toFixed(1)} turns)\n`,
        );
      }
    }

    console.log(`\n### dice=${diceSetName} target=${target}\n`);
    console.log(`| vs | ${PRESET_NAMES.join(' | ')} | avg win% |`);
    console.log(`|---|${PRESET_NAMES.map(() => '---').join('|')}|---|`);
    for (const p of PRESET_NAMES) {
      const cells = PRESET_NAMES.map((q) => (q === p ? '—' : pct(matrix[p][q])));
      const others = PRESET_NAMES.filter((q) => q !== p).map((q) => matrix[p][q]);
      const avg = others.reduce((s, x) => s + x, 0) / others.length;
      console.log(`| **${p}** | ${cells.join(' | ')} | **${pct(avg)}** |`);
    }
  }
}

process.stderr.write(`done in ${((Date.now() - started) / 1000).toFixed(0)}s\n`);
