// Companion to tactics-report.mjs: a finer target curve for one high-contrast
// pairing (aggressive vs cautious, ordinary dice) to show the trend a coarse
// 3-point grid can only hint at.
import { runSimulation, createPreset } from '@farkle/bots';
import { DICE, DICE_PER_TURN } from '@farkle/engine';

const MATCHES = Number(process.argv[2] ?? 10000);
const TARGETS = [500, 1000, 1500, 2000, 3000, 5000, 8000, 12000];
const loadout = new Array(DICE_PER_TURN).fill(DICE['balanced']);

console.log(`<!-- generated by scripts/dice-balance/tactics-trend.mjs, ${MATCHES} matches/target -->`);
console.log(`\n### aggressive vs cautious, ordinary dice, by target\n`);
console.log(`| target | aggressive win% | CI95 | avg turns/match |`);
console.log(`|---|---|---|---|`);

const started = Date.now();
for (const target of TARGETS) {
  const report = runSimulation({
    matches: MATCHES,
    seed: 0xa9c711 ^ target,
    target,
    loadoutA: loadout,
    loadoutB: loadout,
    makeA: (s) => createPreset('aggressive', s),
    makeB: (s) => createPreset('cautious', s),
  });
  const [lo, hi] = report.a.winRateCI95;
  console.log(
    `| ${target} | ${(report.a.winRate * 100).toFixed(1)} | [${(lo * 100).toFixed(1)},${(hi * 100).toFixed(1)}] | ${report.avgTurnsPerMatch.toFixed(1)} |`,
  );
  process.stderr.write(`[${((Date.now() - started) / 1000).toFixed(0)}s] target=${target} done\n`);
}
process.stderr.write(`done in ${((Date.now() - started) / 1000).toFixed(0)}s\n`);
